// PAPER 5: SSC CGL Tier-I (Held On: 26 September 2024, Shift-2)
const PAPER5 = {
  id: "p5",
  title: "SSC CGL Tier-I — 26 Sep 2024 (Shift 2)",
  sections: [
    { name: "General Intelligence and Reasoning", range: [1, 25] },
    { name: "General Awareness", range: [26, 50] },
    { name: "Quantitative Aptitude", range: [51, 75] },
    { name: "English Comprehension", range: [76, 100] }
  ],
  questions: [
{n:1,q:"Select the combination of letters that when sequentially placed in the blanks of the given series will complete the series.\nABC_FG_JK_MOPQ_TUV_Y",o:["DHLRW","DHLSX","EHLRX","EHLRW"],a:3},
{n:2,q:"In a certain code language, 'FUTURE' is written as 'IXWXUH' and 'ISLAND' is written as 'LVODQG'. How will 'JERSEY' be written in that language?",o:["KHTUHA","MHTVGB","MHUVHB","KGTVGA"],a:2},
{n:3,q:"Read the given statements and conclusions carefully.\nStatements:\nAll Grapes are Berries.\nSome Berries are Juices.\nAll Juices are Sodas.\nConclusions:\n(I) Some Berries are Grapes.\n(II) Some Sodas are Berries.",o:["Only conclusion (I) follows","Only conclusion (II) follows","Both the conclusions (I) and (II) follow","Both the conclusions (I) and (II) do not follow"],a:2},
{n:4,q:"Select the option figure in which the given figure (X) is embedded (rotation is NOT allowed).",o:["Option 1","Option 2","Option 3","Option 4"],a:2},
{n:5,q:"Each of the letters in the word 'DARKEN' is arranged in the English alphabetical order.\nHow many letters are there in the English alphabetical series between the letter which is second from the left end and the one which is third from the right end in the new letter-cluster thus formed?",o:["Five","Eight","Six","Seven"],a:2},
{n:6,q:"A sheet of paper is folded along the dotted line successively along the directions shown and is then punched in the last. How would this paper look when unfolded?",o:["Option 1","Option 2","Option 3","Option 4"],a:1},
{n:7,q:"How many triangles are there in the figure given below?",o:["8","10","12","14"],a:1},
{n:8,q:"Six numbers 5, 3, 6, 7, 9 and 2 are written on different faces of a dice. Two positions of this dice are shown in the figure below. Find the number on the face opposite to the one having 5.",o:["2","9","3","6"],a:0},
{n:9,q:"'Conceal' is related to 'Disclose' in the same way as 'Identical' is related to '..........'.\n(The words must be considered as meaningful English words and must not be related to each other based on the number of letters/number of consonants/vowels in the word.)",o:["Similar","Analogous","Distinct","Homogeneous"],a:2},
{n:10,q:"Select the number that will come in the place of the question mark(?), if '+' and '\u2013' are interchanged and '\u00d7' and '\u00f7' are interchanged\n11 \u00f7 8 \u2013 78 \u00d7 6 + 37 = ?",o:["62","64","58","71"],a:1},
{n:11,q:"Select the set in which the numbers are related in the same way as are the numbers of the following set.\n3 \u2014 20 \u2014 5\n4 \u2014 17 \u2014 3\nNOTE: Operations should be performed on the whole numbers, without breaking down the numbers into its constituent digits.",o:["8 \u2014 36 \u2014 11","5 \u2014 28 \u2014 9","9 \u2014 77 \u2014 8","11 \u2014 28 \u2014 5"],a:2},
{n:12,q:"Select the set in which the numbers are related in the same way as are the numbers of the following sets.\n(16, 7, 112)\n(8, 12, 96)",o:["(13, 7, 96)","(14, 9, 128)","(12, 5, 65)","(15, 8, 120)"],a:3},
{n:13,q:"Which figure should replace the question mark (?) if the following series is to be continued?",o:["Option 1","Option 2","Option 3","Option 4"],a:1},
{n:14,q:"In a certain code language\n'A + B' means 'A is the mother of B';\n'A \u2212 B' means 'A is the brother of B';\n'A \u00d7 B' means 'A is the wife of B' and\n'A \u00f7 B' means 'A is the father of B'.\nBased on the above, how is I related to H if 'B + R \u00d7 I \u2212 T \u00f7 H'?",o:["Brother","Father's brother","Father's sister","Father's father"],a:1},
{n:15,q:"Identify the figure given in the options which when put in place of the question mark (?) will logically complete the series?",o:["Option 1","Option 2","Option 3","Option 4"],a:0},
{n:16,q:"Four letter-clusters have been given, out of which three are alike in some manner and one is different. Select the letter-cluster that is different.\nNote: The odd one out is not based on the number of consonants/vowels or their position in the letter cluster",o:["PRUZ","ORTU","MORW","XZCH"],a:1},
{n:17,q:"The second number in the given number pairs is obtained by performing certain mathematical operation(s) on the first number. The same operation(s) are followed in all the number pairs except one. Find that odd number pair.",o:["34 : 44","23 : 25","35 : 36","13 : 16"],a:0},
{n:18,q:"Two different positions of the same dice with faces Z, G, M, F, H and S are shown below. Select the letter that will be on the face opposite to the one having G.",o:["S","F","H","M"],a:1},
{n:19,q:"Two sets of numbers are given below. Which of the given options follows the same set of operations as in the given sets?\n48 \u2013 50 \u2013 46 \u2013 52; 37 \u2013 39 \u2013 35 \u2013 41",o:["26 \u2013 28 \u2013 24 \u2013 30","21 \u2013 23 \u2013 29 \u2013 27","19 \u2013 17 \u2013 21 \u2013 25","15 \u2013 13 \u2013 9 \u2013 19"],a:0},
{n:20,q:"Select the number from among the given options that can replace the question mark (?) in the following series.\n176,167,156,147,136, ?",o:["126","119","127","124"],a:2},
{n:21,q:"Which of the four options will replace the question mark (?) in the following series?\nFX32, EV38, DT44, CR50, ?",o:["BP56","CR54","DP55","CQ55"],a:0},
{n:22,q:"What will come in the place of '?' in the following equation, if '\u00f7' and '\u2013' are interchanged and '\u00d7' and '+' are interchanged?\n7 + 4 \u00f7 18 \u2013 3 \u00d7 2 = ?",o:["18","16","24","20"],a:2},
{n:23,q:"Which of the following terms will replace the question mark (?) in the given series?\nQGMW, VCPU, AYSS, ? , KQYO",o:["FUVQ","FTUO","FVQO","FUXO"],a:0},
{n:24,q:"In a certain code language, 'D' is coded as '16', 'B' is coded as '4' and 'T' is coded as '400'. How will 'H' be coded in the same language?",o:["36","64","25","8"],a:1},
{n:25,q:"In a certain code language, 'bright colour rainbow' is coded as 'mq bj st' and 'sunny bright day' is coded as 'nv bj fm'. How is 'bright' coded in that language?",o:["st","mq","nv","bj"],a:3},
{n:26,q:"At the 36th National Games, Hashika Ramchandra won six gold medals in which of the following sports?",o:["Swimming","Boxing","Wrestling","Badminton"],a:0},
{n:27,q:"Which state in India was the most transformed by the Green Revolution?",o:["Kerala","Maharashtra","Punjab","West Bengal"],a:2},
{n:28,q:"Which of the following ports was developed as a Satellite port to relieve the pressure at the Mumbai port?",o:["Marmagao Port","New Mangalore Port","Deendayal Port Authority","Jawaharlal Nehru Port"],a:3},
{n:29,q:"Who among the following was the shortest-serving Prime Minister of India?",o:["Atal Bihari Vajpayee","Gulzarilal Nanda","Chandra Shekhar","Charan Singh"],a:1},
{n:30,q:"In the context of Mathura school of Art, during which of the following periods were a number of sculptures of Brahmanical deities, such as Kartikeya, Vishnu and Kubera carved?",o:["Satavahana","Shaka","Parthian","Kushana"],a:3},
{n:31,q:"In which of the following situations does the government run a deficit budget?",o:["When the government expenditure and revenue both are zero.","When the government revenue exceeds expenditure.","When the government expenditure equals revenue.","When the government expenditure exceeds revenue."],a:3},
{n:32,q:"Tsang Po and Jamuna are other names of which river?",o:["Narmada","Indus","Ganga","Brahmaputra"],a:3},
{n:33,q:"Which of the following groups/parties was started in San Francisco, United States of America during the Indian National Movement?",o:["Khilafat Committee","Ghadar Party","Swaraj Party","Hindustan Socialist Republican Association"],a:1},
{n:34,q:"Which of the following organisations is NOT a winner of the $100,000 cash prize as 'Best Small Business: Good Food for All', announced by the United Nations?",o:["Edible Routes Private Limited","Oorja Development Solutions India Private Limited","Taru Naturals","Patanjali"],a:3},
{n:35,q:"'Castling' is related to which of the following sports?",o:["Chess","Billiards","Tennis","Table tennis"],a:0},
{n:36,q:"What is the cost of the 'Nand Baba Milk Mission' scheme launched by the Uttar Pradesh state government in 2023?",o:["\u20b92,000 crore","\u20b91,500 crore","\u20b9500 crore","\u20b91,000 crore"],a:3},
{n:37,q:"In the context of vernier calliper, an internal jaw is used to measure:",o:["the depth of a beaker","the length correct up to 1 mm","the length of a rod and diameter of a sphere","the internal diameter of a hollow cylinder and pipes"],a:3},
{n:38,q:"Match the terms in column A with their respective properties in column B.\ni. Glucose ii. Yeast iii. Glycolysis iv. Pyruvic acid\na. Intermediate substance in breakdown of glucose b. Glucose is converted into pyruvic c. Uses nutrients for fermentation process d. Best organic substrate for respiration",o:["i-d, ii-c, iii-b, iv-a","i-b, ii-d, iii-a, iv-c","i-a, ii-b, iii-c, iv-d","i-b, ii-a, iii-d, iv-c"],a:0},
{n:39,q:"If a bar magnet is hung from a string, in which direction does its north pole point?",o:["North","South","East","West"],a:0},
{n:40,q:"Match the points under Column A with those under Column B.\ni. Hexapoda ii. Crustacea iii. Myriapoda iv. Chelicerata\na. Daphnia b. Mosquito c. Limulus d. Julus",o:["i-b, ii-a, iii-d, iv-c","i-d, ii-c, iii-b, iv-a","i-a, ii-b, iii-c, iv-d","i-b, ii-c, iii-a, iv-d"],a:0},
{n:41,q:"Fugdi dance is associated with which of the following states?",o:["Uttar Pradesh","Goa","Kerala","Uttarakhand"],a:1},
{n:42,q:"The concept of 'Independence of judiciary' in the Indian Constitution is taken from the Constitution of:",o:["France","Britain","Ireland","The USA"],a:3},
{n:43,q:"Umayalpuram K Sivaraman is an eminent musician associated with which of the following musical instruments?",o:["Dhol","Sitar","Mridangam","Guitar"],a:2},
{n:44,q:"Rottela Panduga or the Roti Festival is celebrated in which Indian state?",o:["Maharashtra","Andhra Pradesh","Tamil Nadu","Karnataka"],a:1},
{n:45,q:"Belur Math was founded by which of the following social reformers in British India?",o:["KT Telang","Swami Vivekanand","VN Mandlik","RG Bhandarkar"],a:1},
{n:46,q:"Which of the following parts of the mountain will receive the most rainfall from moisture-laden winds?",o:["Leeward side","Relief side","Upward side","Windward side"],a:3},
{n:47,q:"Which singer from Assam was posthumously awarded the Bharat Ratna in 2019?",o:["Rameshwar Pathak","Padmanav Bordoloi","Archana Mahanta","Bhupen Hazarika"],a:3},
{n:48,q:"Medini Rai of Chanderi, Hasan Khan of Mewat and Mahmud Lodi joined Rana Sanga with their forces to fight against which of the following Mughal rulers?",o:["Aurangzeb","Humayun","Babur","Akbar"],a:2},
{n:49,q:"Which writ is issued by a high court or supreme court when a lower court has considered a case going beyond its jurisdiction?",o:["Certiorari","Quo Warrant","Habeas Corpus","Prohibition"],a:3},
{n:50,q:"As per the UNDP, the rank of Sri Lanka in the Human Development Index (2022) is:",o:["72/189","74/189","75/189","73/189"],a:3},
{n:51,q:"If 8cot\u03b8 = 7 then the value of (1 + sin\u03b8)/cos\u03b8 is:",o:["(1+\u221a113)/8","(7+\u221a113)/8","(1+\u221a113)/7","(8+\u221a113)/7"],a:3},
{n:52,q:"The table shows distribution of employees in four companies in 2022 (zones, avg employees/zone, M:F ratio). Company D: 25 zones, 450 avg, 5:4 ratio. Find the total number of male employees working in company D in 2022.",o:["6000","6750","6500","6250"],a:3},
{n:53,q:"The side BC of \u2206ABC is produced to a point D. If AC = BC and \u2220BAC = 70\u00b0, then find the value of 2.5\u2220ACD \u2212 1.5\u2220ABC.",o:["235\u00b0","245\u00b0","225\u00b0","230\u00b0"],a:1},
{n:54,q:"The marked price of an electronic watch in a store is \u20b915,620 and it is available at a discount of 27%. What is the price (in \u20b9, to the nearest tens) that a customer pays if he buys from the store?",o:["11,400","9,880","2,500","10,800"],a:0},
{n:55,q:"The five-digit number 45yz0 is divisible by 40. What is the maximum possible value of (y + z)?",o:["16","18","7","5"],a:0},
{n:56,q:"If x = \u221a6 + 2 and y = \u221a6 \u2013 2, then what is the value of (x/y + y/x)\u00b2 \u2013 3?",o:["22","35","42","97"],a:3},
{n:57,q:"Study the given bar graph (deaths in cities 1-4 across months). The average number of deaths that occurred during April across all the cities (rounded off to the next integer) is:",o:["953","965","928","934"],a:3},
{n:58,q:"If a : b = c : d = e : f = 5 : 7, then what is the ratio (3a + 5c + 11e) : (3b + 5d + 11f)?",o:["11 : 7","3 : 7","7 : 11","5 : 7"],a:3},
{n:59,q:"Varun and Raju, working together, can complete a job in 40 hours whereas Varun alone can complete the same job in 50 hours. The number of hours required by Raju to complete the job alone is:",o:["170","150","200","190"],a:2},
{n:60,q:"What principal would amount to \u20b921,420 in 2 years at the rate of 9.5% p.a. simple interest?",o:["\u20b916,000","\u20b912,000","\u20b911,273","\u20b918,000"],a:3},
{n:61,q:"Raman fixes the sale price of his goods at 16% above the cost price. He sells his goods at 12% less than the fixed price. Find the profit percentage correct to two places of decimal.",o:["0.08%","2.08%","1.07%","3.01%"],a:1},
{n:62,q:"If 2a \u2013 b = 3 and 8a\u00b3 \u2013 b\u00b3 = 999, then find the value of 4a\u00b2 \u2013 b\u00b2.",o:["61","65","67","63"],a:3},
{n:63,q:"If the radius and height of a right circular cylinder are 21 cm and 5 cm, respectively, then the total surface area of the cylinder is (use \u03c0 = 22/7):",o:["3432 cm\u00b2","5212 cm\u00b2","3816 cm\u00b2","4312 cm\u00b2"],a:0},
{n:64,q:"If p = sinA/(1+cosA), then sinA/(1-cosA) is equal to:",o:["p \u2013 1","1/p","1/(1\u2013p)","1/(p+1)"],a:1},
{n:65,q:"A thief takes off on his bike at a certain speed, after seeing a police car at a distance of 250 m. The police car starts chasing the thief and catches him. If the thief runs 1.5 km before being caught and the speed of the police car is 70 km/h, then what is the speed of thief's bike (in km/h)?",o:["65","50","55","60"],a:3},
{n:66,q:"Study the data: shares of 5 partners totalling 10 lakh shares. If Jeevan offers to sell 20,000 of his shares to Meera, how many shares will Meera have? (Meera's current share: 45%)",o:["4,60,000","4,80,000","4,70,000","5,10,000"],a:2},
{n:67,q:"The sum of two consecutive even numbers is 174. Find the smaller number.",o:["86","84","88","90"],a:0},
{n:68,q:"The central angle of a sector is 80\u00b0 and whose length is 96\u03c0. What is the radius of the circle?",o:["196 units","216 units","204 units","116 units"],a:1},
{n:69,q:"Simplify the following expression.\n(60 + 64 \u00f7 4 of 4) \u00d7 {1000 \u00f7 ((10 of (3 + 2)) \u00d7 2 of 5)} \u2212 28 + (100 \u00d7 3 of 3).",o:["1000","100","500","600"],a:0},
{n:70,q:"In \u2206 ABC, DE|| BC and 5 AE = 3EC. If AB = 6.4 units, then the value of DB (in units) is:",o:["3.2","5","4","2.4"],a:2},
{n:71,q:"In a circle with centre O, an arc ABC subtends an angle of 138\u00b0 at the centre of the circle. The chord AB is produced to a point P. Then, the measure of \u2220CBP is:",o:["42\u00b0","111\u00b0","69\u00b0","108\u00b0"],a:2},
{n:72,q:"The bar graph shows turnover of five companies (in crores) across 2017-18, 2018-19, 2019-20. What is the difference between the average sales turnover of all companies between 2018-19 and 2019-20?",o:["\u20b92 crore","\u20b95 crore","\u20b96.5 crore","\u20b93.5 crore"],a:1},
{n:73,q:"Suresh's expenditure and savings are in the ratio of 3 : 1. His income increases by 25%. If his savings increase by 20%, then by how much percentage does his expenditure increase?",o:["26(2/3)%","27(2/3)%","25(2/3)%","28(2/3)%"],a:0},
{n:74,q:"Half litre of a solution contains 15% of alcohol. To change the alcohol concentration to 50%, find the quantity of alcohol to be mixed.",o:["400 ml","350 ml","175 ml","250 ml"],a:1},
{n:75,q:"In a \u2206ABC, right angled at B if tan C = \u221a3 then find (sin\u00b2C+cos\u00b2C)/(1+cot\u00b2C)",o:["16/3","3/4","3/16","4/15"],a:1},
{n:76,q:"Select the INCORRECTLY spelt word.",o:["Accessibility","Apparatus","Aptitude","Atrocios"],a:3},
{n:77,q:"Identify the error in the given sentence.\nMy colleague always works latest than me.",o:["My colleague","latest","than me.","always works"],a:1},
{n:78,q:"Select the option that can be used as a one-word substitute for the given group of words.\nLoud enough to be heard.",o:["Audit","Audacity","Audacious","Audible"],a:3},
{n:79,q:"Identify from the given options the word which is similar in meaning to the following word.\nMunificent",o:["Miserly","Malicious","Underappreciated","Magnanimous"],a:3},
{n:80,q:"Parts of a sentence are given below in jumbled order. Arrange the parts in the correct order to form a meaningful sentence.\nP) once said Q) a wise man R) that action speaks S) louder than words",o:["SQPR","QSRP","PQRS","QPRS"],a:3},
{n:81,q:"Select the most appropriate option to fill in the blank.\nJust bite the ............. and tell him the truth.",o:["shot","gun","dust","bullet"],a:3},
{n:82,q:"Select the option that expresses the opposite meaning of the underlined word.\nIn front of the big screen, this behaviour is generally considered taboo.",o:["Prescription","Obedience","Promotion","Acceptable"],a:3},
{n:83,q:"Select the most appropriate option that can substitute the underlined word in the given sentence.\nVerity is a good virtue for human life.",o:["Truth","Information","Knowledge","Cooperation"],a:0},
{n:84,q:"Parts of a sentence are given below in jumbled order. Arrange the parts in the correct order to form a meaningful sentence.\nFounding father / is / of / New Historicism / Greenbalt / considered / the.",o:["Greenbelt is the founding father of New Historicism considered.","Greenbalt is considered the founding father of New Historicism.","The founding father of New Historicism is considered Greenbalt.","The founding father is considered Greenbalt of New Historicism."],a:1},
{n:85,q:"Select the most appropriate verb / verb phrase to fill in the blank.\nThe team .............................. the championship before their star player got injured.",o:["has won","was won","win","had won"],a:3},
{n:86,q:"Select the correct ANTONYM of the underlined word to fill in the blank and complete the following sentence.\nHe is always active in a party but ............. in the class.",o:["angry","inert","careless","naughty"],a:1},
{n:87,q:"Select the most appropriate option that can rectify the incorrectly spelt word in the following sentence.\nIn our quest for power, we often fail to acknowlege the existence of other people.",o:["acknowledge","accknowledge","acknowlede","acknowledje"],a:0},
{n:88,q:"Select the option that can be used as a one-word substitute for the given group of words.\nMoney collected from people for a cause.",o:["Deposit","Fund","Collection","Savings"],a:1},
{n:89,q:"Select the most appropriate meaning of the underlined idiom.\nBincy's mother kept her cards close to her chest.",o:["Kept her plans and thoughts hidden","Informed that all the cards must be kept safe","Kept her purse and money by herself","Decided to show more affection"],a:0},
{n:90,q:"Select the option that expresses the following sentence in active voice.\nThe issue has been successfully resolved by the customer care team.",o:["The customer care team has successfully resolved the issue.","The issue has successfully resolved the customer care team.","The customer care team successfully resolves the issue.","The customer care team successfully resolved the issue."],a:0},
{n:91,q:"Select the most appropriate option to fill in the blank.\nI like bread made up of corn ................. .",o:["failure","floor","flour","flower"],a:2},
{n:92,q:"Sentences of a paragraph are given below in jumbled order. Arrange the sentences in the correct order to form a meaningful and coherent paragraph.\nA. He remembered her as she once was \u2013 an eager, glowing girl.\nB. He had not seen her for nearly thirteen years.\nC. Mr. Satterthwaite went to meet her.\nD. And now he saw \u2013 a Frozen Lady.",o:["CBAD","ABCD","DBAC","DCBA"],a:0},
{n:93,q:"Select the option that expresses the following sentence in passive voice.\nGill scored 3 centuries in Tata IPL 2023.",o:["3 centuries had been scored by Gill in Tata IPL 2023.","3 centuries were scored by Gill in Tata IPL 2023.","3 centuries has been scored by Gill in Tata IPL 2023.","3 centuries were being scored by Gill in Tata IPL 2023."],a:1},
{n:94,q:"Select the most appropriate ANTONYM of the given word.\nInsert",o:["Remove","Select","Inject","Inform"],a:0},
{n:95,q:"Select the most appropriate SYNONYM of the given word.\nCarcass",o:["Scrap","Corpse","Prison","Gale"],a:1},
{n:96,q:"Cloze passage: Select the most appropriate option to fill in blank no. 1.\n\"Social media companies (1) ______ claim that they promote democracy...\"",o:["never","don't","frequently","seldom"],a:2},
{n:97,q:"Cloze passage: Select the most appropriate option to fill in blank number 2.\n\"The assertion (2) ______ entirely unfounded.\"",o:["cannot","may not be","should","shall"],a:1},
{n:98,q:"Cloze passage: Select the most appropriate option to fill in blank number 3.\n\"Recent history shows how (3) ______ citizens have been mobilised against totalitarian regimes...\"",o:["neutral","alien","foreign","common"],a:3},
{n:99,q:"Cloze passage: Select the most appropriate option to fill in blank number 4.\n\"...digital networks (4) ______ indispensable in bringing together critical voices...\"",o:["can","were","that","have been"],a:3},
{n:100,q:"Cloze passage: Select the most appropriate option to fill in blank number 5.\n\"...critical voices against social and political (5) ______\"",o:["democracy","election","justice","injustice"],a:3}
  ]
};
